### ISSUE TITLE
In the Magento "Component manager" permanent "Please wait..."

### ISSUE THREAD

**Issue by levasc** [bitExpert/magento2-force-login#40]
In Chrome > Inspect > I see error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" and link to https://www.armota.lt/setup/index.php/componentGrid/components, after oppening which I see: 
An error occurred during execution; please try again later.

Additional information:

RuntimeException

File:
/var/www/armota/setup/src/Magento/Setup/Model/PackagesData.php:88
Message:
Couldn't get available versions for package bitexpert/magento2-force-customer-login
Stack trace:
#0 /var/www/armota/setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
#1 /var/www/armota/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /var/www/armota/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4 /var/www/armota/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5 /var/www/armota/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6 /var/www/armota/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /var/www/armota/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9 /var/www/armota/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 /var/www/armota/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/armota/setup/index.php(31): Zend\Mvc\Application->run()
#12 {main}

**Comment by levasc** [comment]
Probably not this component related issue, but global magento:
https://github.com/magento/magento2/issues/6718

**Comment by cookiekiller** [comment]
@levasc I tried it with another composer module, but error didn't show up. Can you give me 2-3 examples when this should crash?

**Comment by isanat** [comment]
Where is a solution ??

**Comment by websharp** [comment]
hi @isanat,

depends on your problem? As I describe before referring to the report, this is an issue may coming from theme itself and has to be fixed in the theme potentially. This is hard to tell, as we do not have this theme to analyze, but got an issue report by another user with another theme. After analyzing that theme, the misusage of the object manager usage directly instead of using the DI concept of Magento2 itself by configuration and annotation has been the reason for this kind of issue reported initially.

Do you want to specify your problem in more detail?

**Comment by isanat** [comment]
Theme default magneto 2.

**Comment by websharp** [comment]
Hi @isanat 

I'm sorry, but I cannot follow your issue. The page you posted is reachable and can be visited. Please describe your issue in detail, or open a new issue, if it is not related to this issue.

Which version of the module are you using?

The module is tested on magento community edition 2.1.5 working fine, please try the current master branch version to have the latest features, it's to final but should be stable.

See more https://github.com/bitExpert/magento2-force-login/blob/master/README.md
