### ISSUE TITLE
Error in admin pages due to invalid XML

### ISSUE THREAD

**Issue by maderlock** [bitExpert/magento2-force-login#81]
This is in Magento 2.1.7.
When visiting pages like a cart rule, I get the following error:
```
1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /Volumes/Sites/SomeSite/vendor/bitexpert/magento2-force-customer-login/etc/adminhtml/system.xml:
Element 'resource': This element is not expected.
Line: 7


Exception #0 (Magento\Framework\Exception\LocalizedException): Invalid XML in file /Volumes/Sites/SomeSite/vendor/bitexpert/magento2-force-customer-login/etc/adminhtml/system.xml:
Element 'resource': This element is not expected.
Line: 7

#0 /Volumes/Sites/SomeSite/vendor/magento/framework/Config/Reader/Filesystem.php(127): Magento\Config\Model\Config\Structure\Reader->_readFiles(Object(Magento\Framework\Config\FileIterator))
#1 /Volumes/Sites/SomeSite/vendor/magento/framework/Config/Data/Scoped.php(103): Magento\Framework\Config\Reader\Filesystem->read('adminhtml')
#2 /Volumes/Sites/SomeSite/vendor/magento/framework/Config/Data/Scoped.php(81): Magento\Framework\Config\Data\Scoped->_loadScopedData()
#3 /Volumes/Sites/SomeSite/vendor/magento/module-config/Model/Config/Structure.php(73): Magento\Framework\Config\Data\Scoped->get()
etc.
```

It looks like the <resource> node should be removed from system.xml?

**Comment by websharp** [comment]
Hi @maderlock ,

this seems related to #79 , for which I will provide a pull request soon (placing the resource tag correctly as defined in the XSD).

**Comment by maderlock** [comment]
Looks like #79 should fix this.
